version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
      args:
        - CODECOV_TOKEN=${CODECOV_TOKEN}
    ports:
      - "80:80"
    depends_on:
      - cms-api

  cms-api:
    build:
      context: .
      dockerfile: apps/cms-api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
volumes:
  node_modules:

networks:
  app-network:
    driver: bridge