name: CI
env:
  node-version: 18.x
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - prod
  workflow_dispatch:

jobs:
  Test-All:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
          cache: npm

      - name: Installing Dependencies
        run: npm install

      - name: Installing nx
        run: npm add nx --global

      - name: Installing vitest
        run: npm add vitest --global

      - name: Running nx run-many lint
        run: npx nx run-many --target=lint

      #- name: Running nx frontend test
      #  run: vitest --coverage

      - name: Running nx api test
        run: npx jest --coverage

      - name: Running nx run-many build
        run: npx nx run-many --target=build

      - name: Running nx run-many e2e
        run: npx nx run-many --target=e2e

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
