name: CI
env:
  node-version: 18.x
on:
  push:
    branches:
      - master
      - develop
  pull_request: {}
  workflow_dispatch: {}

jobs:
  Test-Affected:
    if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
          cache: npm

      - name: Installing Dependencies
        run: npm install

      - name: Installing nx
        run: npm i -g @nrwl/cli 

      - name: Running nx affected lint
        run: npm nx affected --target=lint --parallel=3

      - name: Running nx affected test
        run: npm nx affected --target=test --parallel=3 

      - name: Running nx affected build
        run: npm nx affected --target=build --parallel=3

      - name: Running nx affected e2e
        run: npm nx affected --target=e2e

  Test-All:
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}
          cache: npm

      - name: Installing Dependencies
        run: npm install

      - name: Installing nx
        run: npm i -g @nrwl/cli

      - name: Running nx run-many lint
        run: npx nx run-many --target=lint

      - name: Running nx run-many test
        run: npx nx run-many --target=test --coverage 

      - name: Running nx run-many build
        run: npx nx run-many --target=build

      - name: Running nx run-many e2e
        run: npx nx run-many --target=e2e

      - name: Running nx run-many
        run: npx nx run-many --target=build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

